formated_machines = {
    "Tear 01 - Jager TP100",
    "Tear 02 - Texo CF1015",
    "Tear 03 - Jager TP500-1",
    "Tear 04 - Texo CF1035",
    "Tear 05 - Texo HF 324",
    "Tear 06 - Texo HF 820",
    "Tear 07 - Texo TM 872",
    "Tear 08 - Jager TP 500 II",
    "Tear 09 - Jurgens 11.7",
    "Tear 10 - Texo HF 633",
    "Tear 11 - Texo HF 798",
    "Tear 12 - Jurgens 17.4",
    "Tear 13 - Jurgens 10.0",
    "Fehrer NL-19/3",
    "Dilo PMA 82",
    "Hechtenberg",
    "Sixmeter",
    "NLI"
    "CLT-1",
    "CLT-2",
    "Torre de Resfriamento",
    "Konus II",
    "ISO Winder II",
    "Porta Elétrica - Revisão",
    "Hunter 433",
    "QDF Distrubuição Prédio 2000 220V/380V",
    "Saurer",
    "Temafa II",
    "Plataformas",
    "S22 ...",
    "ETE",
    "Gerador",
    "Elevador Predio 2000 ...",
    "Empilhadeira Toyota",
    "Talha 01 CLT-2",
    "Talha 02 CLT-2",
    "Talha 01 CLT-1",
    "Talha 02 CLT-1",
    "Talha 01 Dilo",
    "Talha 02 Dilo",
    "Separador de Óleo ...",
    "Torre de Resfriamento",
    "GA75",
    "Lago",
    "Urdideira - Karl Mayer",
    "Lema IV",
    "BALANÇA DE ENTRADA DE MANTA CLT-2 ...",
    "INDICADOR DE FORÇA HUNTER 433 ...",
    "TRAÇADOR DE ALTURA DIGIMESS",
    "MULTÍMETRO DIGITAL FLUKE MOD..87",
    "MEDIDOR DE FORÇA ''PULL FORCE''",
    "BALANÇA DE ENTRADA DE MANTA CLT-1 ...",
    "Talha 02 HU433",
    "Talha 01 HU433",
    "Talha 04 PSF",
    "Talha 05 PSF",
    "Gerador",
    "QDF Distribuição Agulhamento (área NL19/3) 220/380 ...",
    "QDF Distribuição Acabamento 220V 380V",
    "Maquina de Atar Knotex R 2849",
    "Maquina de Atar Knotex TS/2 9126",
    "Maquina de Atar Knotex ZS/2 7104",
    "AC 01 Restaurante ...",
    "Lema I",
    "Lema III",
    "Lobinha",
    "Talha 04 Tecelagem",
    "Sistema de Vacuo",
    "Torno Multifuncional",
    "ISO Winder IV",
    "ISO Winder III",
    "QDF Distribuição Retorção 220/380V",
    "Talha Revisao",
    "Konus I",
    "QDF Distribuição Pean Seam 220/380V",
    "Ponte Rolante",
    "Talha Ponte Rolante 1",
    "Talha Ponte Rolante 2",
    "Rebocador EZS 130"
}